default: &default
  adapter: postgresql
  encoding: utf8
  username: developer
  password: real2010
  host: localhost
  pool: 25

development:
  <<: *default
  database: matrason_shop_development

test:
  <<: *default
  database: matrason_shop_test
